### ISSUE TITLE
Custom .htaccess file

### ISSUE THREAD

**Issue by northdpole** [Hackademic/hackademic#121]
We could provide our own .htaccess file with configuration we consider secure.
(Our own error pages, some filtering maybe, e.t.c.)

**Comment by NullArgument** [comment]
Ok, i'll do it, but it will be only for Apache web server.

**Comment by gameFace22** [comment]
https://github.com/Hackademic/hackademic/pull/124
https://github.com/Hackademic/hackademic/pull/123
Already I had made a minimal file. More features can be added here ;)
I just wanted to verify what more to include
@northdpole  And sorry,I should have commented before I am working on it

**Comment by NullArgument** [comment]
@gameFace22 ok, don't worry, it's fine :)

**Comment by NullArgument** [comment]
I think this is how it should be: 72775e9fc1cc3351ba12549380929201c3a729d6
:)

**Comment by NullArgument** [comment]
Added a 404 error page.
![screen](https://cloud.githubusercontent.com/assets/8127545/5602498/0101a1d8-935a-11e4-88b3-d332b3ee8da1.png)

Do you like it?

**Comment by NullArgument** [comment]
Added a 403 error page with 0c9b5154471acabefb6a7fbdf9b36ddcd496bba9
![deny](https://cloud.githubusercontent.com/assets/8127545/5602570/1adf7d46-935f-11e4-8394-08ad2090b552.png)

What do you think?

**Comment by pchaigno** [comment]
@NullArgument Looks good! :+1:

Where did you find the images? Are they freely licensed?

**Comment by NullArgument** [comment]
@pchaigno 
The first is from http://css-tricks.com and i have found other websites that use it as well.
The second was found using google image, it haven't got a watermark so i assume it's ok, isn't it?
Otherwise i can create visually similar images on my own using photoshop.

**Comment by lucif3rr** [comment]
I can see that **.htaccess** is already implemented in the next-dev branch but is there a reason why this issue is not closed yet ? Are we planning to do something more ?

Also, 1 issue that I found while using a custom **.htaccess** is that, it will work only if we allow override in **apache2.conf**. In most of the systems, this will not be the case. So should we explicitly mention this somewhere so that the users will manually create an exception for hackademic directory in apache2.conf ?

**Comment by northdpole** [comment]
we have some basic stuff in place but until we add this documentation and some other cool directives maybe it would be nice to leave it open
