### ISSUE TITLE
[Discuss]: Summer Code Sprint ideas

### ISSUE THREAD

**Issue by northdpole** [Hackademic/hackademic#155]
Since the mailing list doesn't support wiki formatting and user tagging, I'm posting the ideas for this year here,  @pchaigno  @gameFace22 @antonis-manaras   I'd really like input on this
keep in mind that chances of getting more than 1 students are low and in that case I'd prefer that we do the tedious migration job and leave the creative tasks for the students.

=== OWASP Hackademic  ===

=== Docker Sandbox for challenges

''' Brief explanation: '''
Background problem to solve:

We are trying to enable users to freely upload vulnerable applications to the platform. 
After some research we concluded that writing a python application that uses docker to deploy challenges would be the best way to go about it.
Also, we need to provide a frontend to manage the deployed containers and integrate our existing analytics gathering system into the dockerized challenges.
The installer of the application should take care of initializing both the cms and the containers without introducing too much complexity.

Proposed solution:

There is an easy to use python library for docker and there should be a frontend managing the containers we can use off the self with minimal modifications.
The feature has already had a poc using linux containers, you can find it in the open merge requests of the project's github page.

''' Expected results '''
* Integrate dockerized challenges in the platform.
* PEP-8 compliant code in all provided python code
* PSR compliant code in all php provided code
* Sphinx/phpdoc friendly comments
* Excellent reliability
* Good performance
* Unit tests / Functional tests
* Good documentation 

''' Prerequisites '''

Some knowledge of test driven development, php, python, docker

''' OWASP Mentors '''

Spyros Gasteratos (spyros.gasteratos@owasp.org)
-- anyone else who already knows of puppet(I think we'll end up writing puppet manifests for installation)
docker, python, php?

=== Javascript Based Development Challenges ===

Brief explanation:
Background Problem to solve:

We are looking for challenges which are aimed towards secure coding.
The user should be served with a piece of vulnerable javascript which fails the unit tests provided.
The user has to fix the vulnerability in a way that makes the unit tests pass.

Example Solution of one of the challenges:
Provide the user with the following code:
''
function sayHi(string userInput){
var hiField = document.getElementById("hiField");
hiField.innerHtml = userInput;
}
''
Use any javascript unit - testing framework to design a set of unit tests which call the function with all sorts of payloads and test if the user seems to have escaped userInput correctly,
we're not looking for completeness a solid proof of concept implementation for future reference is acceptable.

''' Expected Results '''
A complete implementation of challenges covering the top 10 according to our coding standards.

=== Migrate old code to the new coding standards ===

In the last project summit we decided to introduce code style and standards compliance checking for new commits and slowly migrate the old ones to the new setting.
We also decided to prefer contributions with unit tests.

We're looking for someone to assist in this migration. So far we have 0% of the classes in the new standards/coding style but the frontend tests cover a significant part of the platform.
You could help us reach at least 70% line coverage in tests and a similar coverage in standard/code style 

=== New Theme ===

Problem to solve:
Our current theme is from 2012 and looks even older, moreover it could do with some usability improvements. Your job will be to design and implement a new shiny theme for the platform.

**Comment by lucif3rr** [comment]
I think **Javascript Based Development Challenges** should be avoided this time for the following reasons

* From what I have learned (by playing around with unit testing), it is sure that if we want to develop challenges, it's possible but not in an effective way. Since unit testing is not actually meant for something like this, we have to see how can we get it to work for our advantage.

* This means we have the Proof of concept, that, if we want to, we can develop it but I suggest we can put this idea at a later point of time (I will research more on this and will see if we have a more effective way of implementing the same).

The **New template** and **Migrate old code to the new coding standards** seems to be good one. Also I think we can add the **Gamification** or **Student performance analytics** idea from the [OWASP GSoC 2015 Ideas](https://www.owasp.org/index.php/GSoC2015_Ideas) if you have a correct plan on how to implement it.

IMHO, since we have only very little seats + Stipend for the work, I strongly suggest that students should be motivated to work for more solid ideas than proof of concepts. May be we can introduce ideas like **JavaScript challenges** in OWCS at a later point of time this year where students get enough time to research (Also if we it is going to happen just like last year, it will announced immediately after code sprint ie, in September itself).

**Comment by northdpole** [comment]
For the Dev Challenges, you're kind of right, however unit testing is the way to go with dev challenges and also since eventually we will have a sandbox it will be a nice second feature to compliment the sandboxing architecture.

Gamification isn't that important right now, we have pressing bugs and refactoring to worry about, we can add it as an idea for winter.

Performance analytics are a visualization problem and they are literally a one page project since we are already gathering the data, it isn't a two month problem.

I'm changing the poc part to actual implementation of challenges covering the top10
