### ISSUE TITLE
Add Install instructions

### ISSUE THREAD

**Issue by kurtcoke** [Hackademic/hackademic#165]
You guys still havn't added the install instructions that I wrote for you.

**Comment by pchaigno** [comment]
No, because I'm working on a Dockerfile so the installation steps will completely change. It should be easier to install and more secure.

**Comment by kurtcoke** [comment]
"No, because I'm working on a Dockerfile so the installation steps will completely change. It should be easier to install and more secure."
People should be able to install it without using Docker. I also dont get why installing it in docker would make it more secure.

**Comment by pchaigno** [comment]
> People should be able to install it without using Docker.

Sure they should and they will. Dockerfile will only (probably) become the recommended way to install Hackademic as it should be easier. Thus, I think we should detailed the required step for Docker instead of the more complicated process ;)
<br>

> I also dont get why installing it in docker would make it more secure.

Because if Hackademic is run in Docker, even if it is exploited by an attacker, he won't be able to break out of the container. Thus the host and other application remain safe. That's only a very succinct and simplified explanation but I'm sure you can find more thorough articles online.

**Comment by kurtcoke** [comment]
I think you probably don't understand docker so you shouldn't be using it. How is docker going to protect the database? The database will still have to run some form of persistent storage in a docker volume such as explained on this tutorial: http://www.alexecollins.com/docker-persistence/

**Comment by pchaigno** [comment]
I'm taking the discussion off GitHub since we're going a bit off-topic ;)
