### ISSUE TITLE
Adding logging support for container daemon runtime error

### ISSUE THREAD

**Issue by a0xnirudh** [Hackademic/hackademic#179]
As of now, the daemon is working properly but if for any chance it fails to work or it crashes, there is no way we can debug this. So logging the errors is essential. See [logging class](https://github.com/Hackademic/hackademic/blob/a0xnirudh/docker/ContainerManager/logging_manager.py).

**Comment by TUArjun** [comment]
Solution :

Put the call to main within a try except block and then log the errors that happen during the runtime using the except block. That way, any unspecified or unmanaged errors will be caught and logged, instead of crashing directly.

I have modified the files to correspond to the solution and have made a pull request  #195 .

**Comment by a0xnirudh** [comment]
Great. Looks like the fix is good and working. I have merged the pull request. Closing this issue now !
