### ISSUE TITLE
Dockerfile uses local proxy

### ISSUE THREAD

**Issue by AmaanC** [Hackademic/hackademic#223]
Having the proxy was what was preventing my Docker build, which is how I found it.

Not sure if this *should be removed* given that it is a developmental branch, but I thought I'd call attention to it just in case it should.

[Here's the exact offending line;](https://github.com/Hackademic/hackademic/blob/a0xnirudh/docker/ContainerManager/Dockerfile#L5) it was introduced in [commit 49485ca3e91cb5aaf5052a30644d9337d3d12a10](https://github.com/Hackademic/hackademic/commit/49485ca3e91cb5aaf5052a30644d9337d3d12a10#diff-f3f4d9c8dc298c8e444f8565c2d36cc9R5).

**Comment by a0xnirudh** [comment]
Yes I am very well aware of that already. Its because of my college network restrictions. You can comment the line out to make it work.

**Comment by pchaigno** [comment]
@a0xnirudh Given that you are the only one who needs this exact proxy, maybe it would be better to remove the line ;)
Maybe you can specify it in your local configuration instead ([Docker proxies](https://docs.docker.com/engine/admin/systemd/#http-proxy))...?

**Comment by a0xnirudh** [comment]
@pchaigno The issue is that I cannot configure docker proxy because this local proxy is only for APT updates. It will not support normal traffic. For normal communication, there should not be any proxy.

Since I was working on my branch, I thought I will leave it like that. Most of the times, when I do some important work, I will forget to remove the line before pushing (Sorry about that !).

Probably I will add this to the README soon so that people won't get confused. If I remove this now, there are good chances that it will come back again (already did that twice and happened again :( )
